export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const GET_BREWERIES_BEGIN="GET_BREWERIES_BEGIN";
export const GET_BREWERIES_SUCCESS="GET_BREWERIES_SUCCESS";
export const GET_BREWERIES_ERROR="GET_BREWERIES_ERROR";

export const GET_BREWERIESINFOBYID_BEGIN="GET_BREWERIESINFOBYID_BEGIN";
export const GET_BREWERIESINFOBYID_SUCCESS="GET_BREWERIESINFOBYID_SUCCESS";
export const GET_BREWERIESINFOBYID_ERROR="GET_BREWERIESINFOBYID_ERROR";

export const GET_BREWERIESREVIEWS_BEGIN="GET_BREWERIESREVIEWS_BEGIN";
export const GET_BREWERIESREVIEWS_SUCCESS="GET_BREWERIESREVIEWS_SUCCESS";
export const GET_BREWERIESREVIEWS_ERROR="GET_BREWERIESREVIEWS_ERROR";

export const CREATE_BREWERIESREVIEWS_BEGIN="CREATE_BREWERIESREVIEWS_BEGIN";
export const CREATE_BREWERIESREVIEWS_SUCCESS="CREATE_BREWERIESREVIEWS_SUCCESS";
export const CREATE_BREWERIESREVIEWS_ERROR="CREATE_BREWERIESREVIEWS_ERROR";

export const MODIFY_BREWERIESREVIEWS_BEGIN="MODIFY_BREWERIESREVIEWS_BEGIN";
export const MODIFY_BREWERIESREVIEWS_SUCCESS="MODIFY_BREWERIESREVIEWS_SUCCESS";
export const MODIFY_BREWERIESREVIEWS_ERROR="MODIFY_BREWERIESREVIEWS_ERROR";


export const DELETE_BREWERIESREVIEWS_BEGIN="DELETE_BREWERIESREVIEWS_BEGIN";
export const DELETE_BREWERIESREVIEWS_SUCCESS="DELETE_BREWERIESREVIEWS_SUCCESS";
export const DELETE_BREWERIESREVIEWS_ERROR="DELETE_BREWERIESREVIEWS_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";
